sudo: required
dist: trusty
language: node_js
node_js:
  - '7'
install:
  - npm install -g truffle
  - npm install -g ethereumjs-testrpc
  - npm install
script:
  - npm test
before_script:
  - testrpc > /dev/null & 
  - sleep 5
after_script:
  - npm run coverage
  - bash <(curl -s https://codecov.io/bash) -f coverage.json