version: 2.0

jobs:
  coverage:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - run:
          name: Install
          command: npm install
      - run:
          name: Coverage
          command: npx truffle run coverage
      - run:
          name: Coveralls
          command: coverage/lcov.info | coveralls

workflows:
  version: 2
  build:
    jobs:
      - coverage
