version: 2.0
aliases:
  - &defaults
    docker:
      - image: circleci/node:10

  - &install
    run:
      name: Install
      command: rm -rf node_modules && npm install

jobs:
  test:
    <<: *defaults
    steps:
      - checkout
      - *install
      - run:
          name: Test
          command: npm test

  coverage:
    <<: *defaults
    steps:
      - checkout
      - *install
      - run:
          name: Coverage
          command: npm run coverage

workflows:
  version: 2
  build:
    jobs:
      - test
      - coverage
